// Copyright 2019 free5GC.org
//
// SPDX-License-Identifier: Apache-2.0
//

/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
	utilLogger "github.com/omec-project/util/logger"
)

const (
	ErrHTTPMethodNotAllowed           = "Method Not Allowed"
	InfluenceDataPath                 = "/application-data/influenceData/:influenceId"
	AMF3GPPAccessSubscriptionPath     = "/subscription-data/:ueId/:servingPlmnId/amf-3gpp-access"
	AMFNon3GPPAccessSubscriptionPath  = "/subscription-data/:ueId/:servingPlmnId/amf-non-3gpp-access"
	InfluenceDataSubscriptionPath     = "/application-data/influenceData/:influenceId/:subscriptionId"
	PFDsByAppIDPath                   = "/application-data/pfds/:appId"
	PolicyBDTDataByReferencePath      = "/policy-data/bdt-data/:bdtReferenceId"
	OperatorSpecificDataPath          = "/policy-data/ues/:ueId/operator-specific-data"
	SmDataByUsageMonIDPath            = "/policy-data/ues/:ueId/sm-data/:usageMonId"
	UEPolicySetPath                   = "/policy-data/ues/:ueId/ue-policy-set"
	SMFRegistrationByPduSessionPath   = "/subscription-data/:ueId/:servingPlmnId/smf-registrations/:pduSessionId"
	SMSF3GPPAccessPath                = "/subscription-data/:ueId/:servingPlmnId/smsf-3gpp-access"
	SMSFNon3GPPAccessPath             = "/subscription-data/:ueId/:servingPlmnId/smsf-non-3gpp-access"
	AMFSubscriptionBySubsIDPath       = "/subscription-data/:ueId/:servingPlmnId/ee-subscriptions/:subsId/amf-subscriptions"
	ExposureSessionManagementDataPath = "/exposure-data/:ueId/session-management-data/:pduSessionId"
	ExposureAccessMobilityDataPath    = "/exposure-data/:ueId/access-and-mobility-data"
)

var subsToNotifyStr = "subs-to-notify"

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. e.g., GET, POST etc.
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := utilLogger.NewGinWithZap(logger.GinLog)
	AddService(router)
	return router
}

func subMsgShortDispatchHandlerFunc(c *gin.Context) {
	op := c.Param("ueId")
	for _, route := range subShortRoutes {
		if strings.Contains(route.Pattern, op) && route.Method == c.Request.Method {
			route.HandlerFunc(c)
			return
		}
	}
	c.String(http.StatusMethodNotAllowed, ErrHTTPMethodNotAllowed)
}

func subMsgDispatchHandlerFunc(c *gin.Context) {
	op := c.Param("servingPlmnId")
	subsToNotify := c.Param("ueId")
	for _, route := range subRoutes {
		if strings.Contains(route.Pattern, op) && route.Method == c.Request.Method {
			route.HandlerFunc(c)
			return
		}
		// Sepcial case
		if subsToNotify == subsToNotifyStr && strings.Contains(route.Pattern, subsToNotifyStr) && route.Method == c.Request.Method {
			c.Params = append(c.Params, gin.Param{Key: "subsId", Value: c.Param("servingPlmnId")})
			route.HandlerFunc(c)
			return
		}
	}
	c.String(http.StatusMethodNotAllowed, ErrHTTPMethodNotAllowed)
}

func eeMsgShortDispatchHandlerFunc(c *gin.Context) {
	groupData := c.Param("ueId")
	contextData := c.Param("servingPlmnId")
	for _, route := range eeShortRoutes {
		if strings.Contains(route.Pattern, groupData) && route.Method == c.Request.Method {
			c.Params = append(c.Params, gin.Param{Key: "ueGroupId", Value: c.Param("servingPlmnId")})
			route.HandlerFunc(c)
			return
		}
		if strings.Contains(route.Pattern, contextData) && route.Method == c.Request.Method {
			route.HandlerFunc(c)
			return
		}
	}
	c.String(http.StatusMethodNotAllowed, ErrHTTPMethodNotAllowed)
}

func eeMsgDispatchHandlerFunc(c *gin.Context) {
	groupData := c.Param("ueId")
	contextData := c.Param("servingPlmnId")
	for _, route := range eeRoutes {
		if strings.Contains(route.Pattern, groupData) && route.Method == c.Request.Method {
			c.Params = append(c.Params, gin.Param{Key: "ueGroupId", Value: c.Param("servingPlmnId")})
			route.HandlerFunc(c)
			return
		}
		if strings.Contains(route.Pattern, contextData) && route.Method == c.Request.Method {
			route.HandlerFunc(c)
			return
		}
	}
	c.String(http.StatusMethodNotAllowed, ErrHTTPMethodNotAllowed)
}

// Handler to distinguish subsToNotifyStr from ":influenceId".
func appInfluDataMsgDispatchHandlerFunc(c *gin.Context) {
	influID := c.Param("influenceId")
	for _, route := range appInfluDataRoutes {
		if route.Method == c.Request.Method {
			if influID == subsToNotifyStr {
				if strings.Contains(route.Pattern, subsToNotifyStr) {
					route.HandlerFunc(c)
					return
				}
			} else {
				if !strings.Contains(route.Pattern, subsToNotifyStr) {
					route.HandlerFunc(c)
					return
				}
			}
		}
	}
	c.String(http.StatusMethodNotAllowed, ErrHTTPMethodNotAllowed)
}

func expoMsgDispatchHandlerFunc(c *gin.Context) {
	subsToNotify := c.Param("ueId")
	op := c.Param("subId")
	for _, route := range expoRoutes {
		if strings.Contains(route.Pattern, op) && route.Method == c.Request.Method {
			route.HandlerFunc(c)
			return
		}
		if subsToNotify == subsToNotifyStr && strings.Contains(route.Pattern, subsToNotifyStr) && route.Method == c.Request.Method {
			route.HandlerFunc(c)
			return
		}
	}
	c.String(http.StatusMethodNotAllowed, ErrHTTPMethodNotAllowed)
}

func AddService(engine *gin.Engine) *gin.RouterGroup {
	group := engine.Group("/nudr-dr/v2")

	for _, route := range routes {
		switch route.Method {
		case "GET":
			group.GET(route.Pattern, route.HandlerFunc)
		case "PATCH":
			group.PATCH(route.Pattern, route.HandlerFunc)
		case "POST":
			group.POST(route.Pattern, route.HandlerFunc)
		case "PUT":
			group.PUT(route.Pattern, route.HandlerFunc)
		case "DELETE":
			group.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	subPatternShort := "/subscription-data/:ueId"
	group.Any(subPatternShort, subMsgShortDispatchHandlerFunc)

	subPattern := "/subscription-data/:ueId/:servingPlmnId"
	group.Any(subPattern, subMsgDispatchHandlerFunc)

	eePatternShort := "/subscription-data/:ueId/:servingPlmnId/ee-subscriptions"
	group.Any(eePatternShort, eeMsgShortDispatchHandlerFunc)

	eePattern := "/subscription-data/:ueId/:servingPlmnId/ee-subscriptions/:subsId"
	group.Any(eePattern, eeMsgDispatchHandlerFunc)

	/*
	 * GIN wildcard issue:
	 * '/application-data/influenceData/:influenceId' and
	 * '/application-data/influenceData/subs-to-notify' patterns will be conflicted.
	 * Only can use '/application-data/influenceData/:influenceId' pattern and
	 * use a dispatch handler to distinguish subsToNotifyStr from ":influenceId".
	 */
	appInfluDataPattern := InfluenceDataPath
	group.Any(appInfluDataPattern, appInfluDataMsgDispatchHandlerFunc)

	expoPatternShort := "/exposure-data/:ueId/:subId"
	group.Any(expoPatternShort, expoMsgDispatchHandlerFunc)

	expoPattern := "/exposure-data/:ueId/:subId/:pduSessionId"
	group.Any(expoPattern, expoMsgDispatchHandlerFunc)

	return group
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		"GET",
		"/",
		Index,
	},

	{
		"HTTPAmfContext3gpp",
		strings.ToUpper("Patch"),
		AMF3GPPAccessSubscriptionPath,
		HTTPAmfContext3gpp,
	},

	{
		"HTTPCreateAmfContext3gpp",
		strings.ToUpper("Put"),
		AMF3GPPAccessSubscriptionPath,
		HTTPCreateAmfContext3gpp,
	},

	{
		"HTTPQueryAmfContext3gpp",
		strings.ToUpper("Get"),
		AMF3GPPAccessSubscriptionPath,
		HTTPQueryAmfContext3gpp,
	},

	{
		"HTTPAmfContextNon3gpp",
		strings.ToUpper("Patch"),
		AMFNon3GPPAccessSubscriptionPath,
		HTTPAmfContextNon3gpp,
	},

	{
		"HTTPCreateAmfContextNon3gpp",
		strings.ToUpper("Put"),
		AMFNon3GPPAccessSubscriptionPath,
		HTTPCreateAmfContextNon3gpp,
	},

	{
		"HTTPQueryAmfContextNon3gpp",
		strings.ToUpper("Get"),
		AMFNon3GPPAccessSubscriptionPath,
		HTTPQueryAmfContextNon3gpp,
	},

	{
		"HTTPQueryAmData",
		strings.ToUpper("Get"),
		"/subscription-data/:ueId/:servingPlmnId/provisioned-data/am-data",
		HTTPQueryAmData,
	},

	{
		"HTTPQueryAuthenticationStatus",
		strings.ToUpper("Get"),
		"/subscription-data/:ueId/:servingPlmnId/authentication-status",
		HTTPQueryAuthenticationStatus,
	},

	{
		"HTTPModifyAuthentication",
		strings.ToUpper("Patch"),
		"/subscription-data/:ueId/:servingPlmnId/authentication-subscription",
		HTTPModifyAuthentication,
	},

	{
		"HTTPQueryAuthSubsData",
		strings.ToUpper("Get"),
		"/subscription-data/:ueId/:servingPlmnId/authentication-subscription",
		HTTPQueryAuthSubsData,
	},

	{
		"HTTPCreateAuthenticationSoR",
		strings.ToUpper("Put"),
		"/subscription-data/:ueId/:servingPlmnId/sor-data",
		HTTPCreateAuthenticationSoR,
	},

	{
		"HTTPQueryAuthSoR",
		strings.ToUpper("Get"),
		"/subscription-data/:ueId/:servingPlmnId/sor-data",
		HTTPQueryAuthSoR,
	},

	{
		"HTTPCreateAuthenticationStatus",
		strings.ToUpper("Put"),
		"/subscription-data/:ueId/:servingPlmnId/authentication-status",
		HTTPCreateAuthenticationStatus,
	},

	{
		"HTTPApplicationDataInfluenceDataGet",
		strings.ToUpper("Get"),
		"/application-data/influenceData",
		HTTPApplicationDataInfluenceDataGet,
	},

	/*
	 * GIN wildcard issue:
	 * '/application-data/influenceData/:influenceId' and
	 * '/application-data/influenceData/subs-to-notify' patterns will be conflicted.
	 * Only can use '/application-data/influenceData/:influenceId' pattern.
	 * Here ":influenceId" value should be subsToNotifyStr.
	 */
	{
		"HTTPApplicationDataInfluenceDataSubsToNotifySubscriptionIdDelete",
		strings.ToUpper("Delete"),
		InfluenceDataSubscriptionPath,
		HTTPApplicationDataInfluenceDataSubsToNotifySubscriptionIdDelete,
	},

	{
		"HTTPApplicationDataInfluenceDataSubsToNotifySubscriptionIdGet",
		strings.ToUpper("Get"),
		InfluenceDataSubscriptionPath,
		HTTPApplicationDataInfluenceDataSubsToNotifySubscriptionIdGet,
	},

	{
		"HTTPApplicationDataInfluenceDataSubsToNotifySubscriptionIdPut",
		strings.ToUpper("Put"),
		InfluenceDataSubscriptionPath,
		HTTPApplicationDataInfluenceDataSubsToNotifySubscriptionIdPut,
	},

	{
		"HTTPApplicationDataPfdsAppIdDelete",
		strings.ToUpper("Delete"),
		PFDsByAppIDPath,
		HTTPApplicationDataPfdsAppIdDelete,
	},

	{
		"HTTPApplicationDataPfdsAppIdGet",
		strings.ToUpper("Get"),
		PFDsByAppIDPath,
		HTTPApplicationDataPfdsAppIdGet,
	},

	{
		"HTTPApplicationDataPfdsAppIdPut",
		strings.ToUpper("Put"),
		PFDsByAppIDPath,
		HTTPApplicationDataPfdsAppIdPut,
	},

	{
		"HTTPApplicationDataPfdsGet",
		strings.ToUpper("Get"),
		"/application-data/pfds",
		HTTPApplicationDataPfdsGet,
	},

	{
		"HTTPPolicyDataBdtDataBdtReferenceIdDelete",
		strings.ToUpper("Delete"),
		PolicyBDTDataByReferencePath,
		HTTPPolicyDataBdtDataBdtReferenceIdDelete,
	},

	{
		"HTTPPolicyDataBdtDataBdtReferenceIdGet",
		strings.ToUpper("Get"),
		PolicyBDTDataByReferencePath,
		HTTPPolicyDataBdtDataBdtReferenceIdGet,
	},

	{
		"HTTPPolicyDataBdtDataBdtReferenceIdPut",
		strings.ToUpper("Put"),
		PolicyBDTDataByReferencePath,
		HTTPPolicyDataBdtDataBdtReferenceIdPut,
	},

	{
		"HTTPPolicyDataBdtDataGet",
		strings.ToUpper("Get"),
		"/policy-data/bdt-data",
		HTTPPolicyDataBdtDataGet,
	},

	{
		"HTTPPolicyDataPlmnsPlmnIdUePolicySetGet",
		strings.ToUpper("Get"),
		"/policy-data/plmns/:plmnId/ue-policy-set",
		HTTPPolicyDataPlmnsPlmnIdUePolicySetGet,
	},

	{
		"HTTPPolicyDataSponsorConnectivityDataSponsorIdGet",
		strings.ToUpper("Get"),
		"/policy-data/sponsor-connectivity-data/:sponsorId",
		HTTPPolicyDataSponsorConnectivityDataSponsorIdGet,
	},

	{
		"HTTPPolicyDataSubsToNotifyPost",
		strings.ToUpper("Post"),
		"/policy-data/subs-to-notify",
		HTTPPolicyDataSubsToNotifyPost,
	},

	{
		"HTTPPolicyDataSubsToNotifySubsIdDelete",
		strings.ToUpper("Delete"),
		"/policy-data/subs-to-notify/:subsId",
		HTTPPolicyDataSubsToNotifySubsIdDelete,
	},

	{
		"HTTPPolicyDataSubsToNotifySubsIdPut",
		strings.ToUpper("Put"),
		"/policy-data/subs-to-notify/:subsId",
		HTTPPolicyDataSubsToNotifySubsIdPut,
	},

	{
		"HTTPPolicyDataUesUeIdAmDataGet",
		strings.ToUpper("Get"),
		"/policy-data/ues/:ueId/am-data",
		HTTPPolicyDataUesUeIdAmDataGet,
	},

	{
		"HTTPPolicyDataUesUeIdOperatorSpecificDataGet",
		strings.ToUpper("Get"),
		OperatorSpecificDataPath,
		HTTPPolicyDataUesUeIdOperatorSpecificDataGet,
	},

	{
		"HTTPPolicyDataUesUeIdOperatorSpecificDataPatch",
		strings.ToUpper("Patch"),
		OperatorSpecificDataPath,
		HTTPPolicyDataUesUeIdOperatorSpecificDataPatch,
	},

	{
		"HTTPPolicyDataUesUeIdOperatorSpecificDataPut",
		strings.ToUpper("Put"),
		OperatorSpecificDataPath,
		HTTPPolicyDataUesUeIdOperatorSpecificDataPut,
	},

	{
		"HTTPPolicyDataUesUeIdSmDataGet",
		strings.ToUpper("Get"),
		"/policy-data/ues/:ueId/sm-data",
		HTTPPolicyDataUesUeIdSmDataGet,
	},

	{
		"HTTPPolicyDataUesUeIdSmDataPatch",
		strings.ToUpper("Patch"),
		"/policy-data/ues/:ueId/sm-data",
		HTTPPolicyDataUesUeIdSmDataPatch,
	},

	{
		"HTTPPolicyDataUesUeIdSmDataUsageMonIdDelete",
		strings.ToUpper("Delete"),
		SmDataByUsageMonIDPath,
		HTTPPolicyDataUesUeIdSmDataUsageMonIdDelete,
	},

	{
		"HTTPPolicyDataUesUeIdSmDataUsageMonIdGet",
		strings.ToUpper("Get"),
		SmDataByUsageMonIDPath,
		HTTPPolicyDataUesUeIdSmDataUsageMonIdGet,
	},

	{
		"HTTPPolicyDataUesUeIdSmDataUsageMonIdPut",
		strings.ToUpper("Put"),
		SmDataByUsageMonIDPath,
		HTTPPolicyDataUesUeIdSmDataUsageMonIdPut,
	},

	{
		"HTTPPolicyDataUesUeIdUePolicySetGet",
		strings.ToUpper("Get"),
		UEPolicySetPath,
		HTTPPolicyDataUesUeIdUePolicySetGet,
	},

	{
		"HTTPPolicyDataUesUeIdUePolicySetPatch",
		strings.ToUpper("Patch"),
		UEPolicySetPath,
		HTTPPolicyDataUesUeIdUePolicySetPatch,
	},

	{
		"HTTPPolicyDataUesUeIdUePolicySetPut",
		strings.ToUpper("Put"),
		UEPolicySetPath,
		HTTPPolicyDataUesUeIdUePolicySetPut,
	},

	{
		"HTTPQueryProvisionedData",
		strings.ToUpper("Get"),
		"/subscription-data/:ueId/:servingPlmnId/provisioned-data",
		HTTPQueryProvisionedData,
	},

	{
		"HTTPRemovesdmSubscriptions",
		strings.ToUpper("Delete"),
		"/subscription-data/:ueId/:servingPlmnId/sdm-subscriptions/:subsId",
		HTTPRemovesdmSubscriptions,
	},

	{
		"HTTPUpdatesdmsubscriptions",
		strings.ToUpper("Put"),
		"/subscription-data/:ueId/:servingPlmnId/sdm-subscriptions/:subsId",
		HTTPUpdatesdmsubscriptions,
	},

	{
		"HTTPCreateSdmSubscriptions",
		strings.ToUpper("Post"),
		"/subscription-data/:ueId/:servingPlmnId/sdm-subscriptions",
		HTTPCreateSdmSubscriptions,
	},

	{
		"HTTPQuerysdmsubscriptions",
		strings.ToUpper("Get"),
		"/subscription-data/:ueId/:servingPlmnId/sdm-subscriptions",
		HTTPQuerysdmsubscriptions,
	},

	{
		"HTTPCreateSmfContextNon3gpp",
		strings.ToUpper("Put"),
		"/subscription-data/:ueId/context-data/smf-registrations/:pduSessionId",
		HTTPCreateSmfContextNon3gpp,
	},

	{
		"HTTPDeleteSmfContext",
		strings.ToUpper("Delete"),
		SMFRegistrationByPduSessionPath,
		HTTPDeleteSmfContext,
	},

	{
		"HTTPQuerySmfRegistration",
		strings.ToUpper("Get"),
		SMFRegistrationByPduSessionPath,
		HTTPQuerySmfRegistration,
	},

	{
		"HTTPQuerySmfRegList",
		strings.ToUpper("Get"),
		"/subscription-data/:ueId/:servingPlmnId/smf-registrations",
		HTTPQuerySmfRegList,
	},

	{
		"HTTPQuerySmfSelectData",
		strings.ToUpper("Get"),
		"/subscription-data/:ueId/:servingPlmnId/provisioned-data/smf-selection-subscription-data",
		HTTPQuerySmfSelectData,
	},

	{
		"HTTPCreateSmsfContext3gpp",
		strings.ToUpper("Put"),
		SMSF3GPPAccessPath,
		HTTPCreateSmsfContext3gpp,
	},

	{
		"HTTPDeleteSmsfContext3gpp",
		strings.ToUpper("Delete"),
		SMSF3GPPAccessPath,
		HTTPDeleteSmsfContext3gpp,
	},

	{
		"HTTPQuerySmsfContext3gpp",
		strings.ToUpper("Get"),
		SMSF3GPPAccessPath,
		HTTPQuerySmsfContext3gpp,
	},

	{
		"HTTPCreateSmsfContextNon3gpp",
		strings.ToUpper("Put"),
		SMSFNon3GPPAccessPath,
		HTTPCreateSmsfContextNon3gpp,
	},

	{
		"HTTPDeleteSmsfContextNon3gpp",
		strings.ToUpper("Delete"),
		SMSFNon3GPPAccessPath,
		HTTPDeleteSmsfContextNon3gpp,
	},

	{
		"HTTPQuerySmsfContextNon3gpp",
		strings.ToUpper("Get"),
		SMSFNon3GPPAccessPath,
		HTTPQuerySmsfContextNon3gpp,
	},

	{
		"HTTPQuerySmsMngData",
		strings.ToUpper("Get"),
		"/subscription-data/:ueId/:servingPlmnId/provisioned-data/sms-mng-data",
		HTTPQuerySmsMngData,
	},

	{
		"HTTPQuerySmsData",
		strings.ToUpper("Get"),
		"/subscription-data/:ueId/:servingPlmnId/provisioned-data/sms-data",
		HTTPQuerySmsData,
	},

	{
		"HTTPQuerySmData",
		strings.ToUpper("Get"),
		"/subscription-data/:ueId/:servingPlmnId/provisioned-data/sm-data",
		HTTPQuerySmData,
	},

	{
		"HTTPQueryTraceData",
		strings.ToUpper("Get"),
		"/subscription-data/:ueId/:servingPlmnId/provisioned-data/trace-data",
		HTTPQueryTraceData,
	},

	{
		"HTTPCreateAMFSubscriptions",
		strings.ToUpper("Put"),
		AMFSubscriptionBySubsIDPath,
		HTTPCreateAMFSubscriptions,
	},

	{
		"HTTPModifyAmfSubscriptionInfo",
		strings.ToUpper("Patch"),
		AMFSubscriptionBySubsIDPath,
		HTTPModifyAmfSubscriptionInfo,
	},

	{
		"HTTPRemoveAmfSubscriptionsInfo",
		strings.ToUpper("Delete"),
		AMFSubscriptionBySubsIDPath,
		HTTPRemoveAmfSubscriptionsInfo,
	},

	{
		"HTTPGetAmfSubscriptionInfo",
		strings.ToUpper("Get"),
		AMFSubscriptionBySubsIDPath,
		HTTPGetAmfSubscriptionInfo,
	},
}

var subRoutes = Routes{
	{
		"HTTPQueryEEData",
		strings.ToUpper("Get"),
		"/subscription-data/:ueId/ee-profile-data",
		HTTPQueryEEData,
	},

	{
		"HTTPPatchOperSpecData",
		strings.ToUpper("Patch"),
		"/subscription-data/:ueId/operator-specific-data",
		HTTPPatchOperSpecData,
	},

	{
		"HTTPQueryOperSpecData",
		strings.ToUpper("Get"),
		"/subscription-data/:ueId/operator-specific-data",
		HTTPQueryOperSpecData,
	},

	{
		"HTTPGetppData",
		strings.ToUpper("Get"),
		"/subscription-data/:ueId/pp-data",
		HTTPGetppData,
	},

	{
		"HTTPModifyPpData",
		strings.ToUpper("Patch"),
		"/subscription-data/:ueId/pp-data",
		HTTPModifyPpData,
	},

	{
		"HTTPGetIdentityData",
		strings.ToUpper("Get"),
		"/subscription-data/:ueId/identity-data",
		HTTPGetIdentityData,
	},

	{
		"HTTPGetOdbData",
		strings.ToUpper("Get"),
		"/subscription-data/:ueId/operator-determined-barring-data",
		HTTPGetOdbData,
	},

	// Special case
	{
		"HTTPRemovesubscriptionDataSubscriptions",
		strings.ToUpper("Delete"),
		"/subscription-data/subs-to-notify/:subsId",
		HTTPRemovesubscriptionDataSubscriptions,
	},
}

var subShortRoutes = Routes{
	{
		"HTTPGetSharedData",
		strings.ToUpper("Get"),
		"/subscription-data/shared-data",
		HTTPGetSharedData,
	},

	{
		"HTTPPostSubscriptionDataSubscriptions",
		strings.ToUpper("Post"),
		"/subscription-data/subs-to-notify",
		HTTPPostSubscriptionDataSubscriptions,
	},
}

var eeShortRoutes = Routes{
	{
		"HTTPCreateEeGroupSubscriptions",
		strings.ToUpper("Post"),
		"/subscription-data/group-data/:ueGroupId/ee-subscriptions",
		HTTPCreateEeGroupSubscriptions,
	},

	{
		"HTTPQueryEeGroupSubscriptions",
		strings.ToUpper("Get"),
		"/subscription-data/group-data/:ueGroupId/ee-subscriptions",
		HTTPQueryEeGroupSubscriptions,
	},

	{
		"HTTPCreateEeSubscriptions",
		strings.ToUpper("Post"),
		"/subscription-data/:ueId/context-data/ee-subscriptions",
		HTTPCreateEeSubscriptions,
	},

	{
		"HTTPQueryeesubscriptions",
		strings.ToUpper("Get"),
		"/subscription-data/:ueId/context-data/ee-subscriptions",
		HTTPQueryeesubscriptions,
	},
}

var eeRoutes = Routes{
	{
		"HTTPRemoveeeSubscriptions",
		strings.ToUpper("Delete"),
		"/subscription-data/:ueId/context-data/ee-subscriptions/:subsId",
		HTTPRemoveeeSubscriptions,
	},

	{
		"HTTPUpdateEesubscriptions",
		strings.ToUpper("Put"),
		"/subscription-data/:ueId/context-data/ee-subscriptions/:subsId",
		HTTPUpdateEesubscriptions,
	},

	{
		"HTTPUpdateEeGroupSubscriptions",
		strings.ToUpper("Put"),
		"/subscription-data/group-data/:ueGroupId/ee-subscriptions/:subsId",
		HTTPUpdateEeGroupSubscriptions,
	},

	{
		"HTTPRemoveEeGroupSubscriptions",
		strings.ToUpper("Delete"),
		"/subscription-data/group-data/:ueGroupId/ee-subscriptions/:subsId",
		HTTPRemoveEeGroupSubscriptions,
	},
}

var expoRoutes = Routes{
	{
		"HTTPCreateSessionManagementData",
		strings.ToUpper("Put"),
		ExposureSessionManagementDataPath,
		HTTPCreateSessionManagementData,
	},

	{
		"HTTPDeleteSessionManagementData",
		strings.ToUpper("Delete"),
		ExposureSessionManagementDataPath,
		HTTPDeleteSessionManagementData,
	},

	{
		"HTTPQuerySessionManagementData",
		strings.ToUpper("Get"),
		ExposureSessionManagementDataPath,
		HTTPQuerySessionManagementData,
	},

	{
		"CreateAccessAndMobilityData",
		strings.ToUpper("Put"),
		ExposureAccessMobilityDataPath,
		CreateAccessAndMobilityData,
	},

	{
		"DeleteAccessAndMobilityData",
		strings.ToUpper("Delete"),
		ExposureAccessMobilityDataPath,
		DeleteAccessAndMobilityData,
	},

	{
		"QueryAccessAndMobilityData",
		strings.ToUpper("Get"),
		ExposureAccessMobilityDataPath,
		QueryAccessAndMobilityData,
	},

	{
		"HTTPExposureDataSubsToNotifyPost",
		strings.ToUpper("Post"),
		"/exposure-data/subs-to-notify",
		HTTPExposureDataSubsToNotifyPost,
	},

	{
		"HTTPExposureDataSubsToNotifySubIdDelete",
		strings.ToUpper("Delete"),
		"/exposure-data/subs-to-notify/:subId",
		HTTPExposureDataSubsToNotifySubIdDelete,
	},

	{
		"HTTPExposureDataSubsToNotifySubIdPut",
		strings.ToUpper("Put"),
		"/exposure-data/subs-to-notify/:subId",
		HTTPExposureDataSubsToNotifySubIdPut,
	},
}

var appInfluDataRoutes = Routes{
	{
		"HTTPApplicationDataInfluenceDataSubsToNotifyGet",
		strings.ToUpper("Get"),
		"/application-data/influenceData/subs-to-notify",
		HTTPApplicationDataInfluenceDataSubsToNotifyGet,
	},

	{
		"HTTPApplicationDataInfluenceDataSubsToNotifyPost",
		strings.ToUpper("Post"),
		"/application-data/influenceData/subs-to-notify",
		HTTPApplicationDataInfluenceDataSubsToNotifyPost,
	},

	{
		"HTTPApplicationDataInfluenceDataInfluenceIdDelete",
		strings.ToUpper("Delete"),
		InfluenceDataPath,
		HTTPApplicationDataInfluenceDataInfluenceIdDelete,
	},

	{
		"HTTPApplicationDataInfluenceDataInfluenceIdPatch",
		strings.ToUpper("Patch"),
		InfluenceDataPath,
		HTTPApplicationDataInfluenceDataInfluenceIdPatch,
	},

	{
		"HTTPApplicationDataInfluenceDataInfluenceIdPut",
		strings.ToUpper("Put"),
		InfluenceDataPath,
		HTTPApplicationDataInfluenceDataInfluenceIdPut,
	},

	{
		"HTTPApplicationDataInfluenceDataSubsToNotifyGet",
		strings.ToUpper("Get"),
		InfluenceDataPath,
		HTTPApplicationDataInfluenceDataSubsToNotifyGet,
	},

	{
		"HTTPApplicationDataInfluenceDataSubsToNotifyPost",
		strings.ToUpper("Post"),
		InfluenceDataPath,
		HTTPApplicationDataInfluenceDataSubsToNotifyPost,
	},
}
